# Generated by Django 5.2.3 on 2025-07-19 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_blog_url_alter_blog_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
